import pandas as pd
import numpy as np
import networkx as nx
from sklearn.covariance import LedoitWolf
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm
import os

def corr_matrix(mode, min_obs=50, min_assets_frac=0.7):
    """
    Compute absolute correlation matrix using a dense
    subpanel of the mode.
    
    Returns both correlation matrix and asset names.
    """
    n_assets = mode.shape[1]

    # Keep dates with enough assets
    valid_rows = mode.notna().sum(axis=1) >= int(min_assets_frac * n_assets)
    X = mode.loc[valid_rows]

    # Keep assets with enough observations
    valid_cols = X.notna().sum(axis=0) >= min_obs
    X = X.loc[:, valid_cols]

    # Drop remaining NaNs (small)
    X = X.dropna(axis=0, how="any")

    if X.shape[0] < min_obs or X.shape[1] < 5:
        raise ValueError("Panel too sparse to compute correlation.")

    lw = LedoitWolf().fit(X.values)
    cov = lw.covariance_

    std = np.sqrt(np.diag(cov))
    corr = cov / np.outer(std, std)

    # Retorna matriz de correlação e nomes dos ativos
    return pd.DataFrame(corr, index=X.columns, columns=X.columns)

def get_network_TMFG(corr_matrix):
    """
    Fast O(N^2) TMFG implementation using vectorized NumPy operations.
    Accepts pandas DataFrame or NumPy array.
    """

    # -----------------------------
    # Handle DataFrame input
    # -----------------------------
    if isinstance(corr_matrix, pd.DataFrame):
        labels = corr_matrix.index.to_list()
        C = corr_matrix.values
    else:
        labels = list(range(corr_matrix.shape[0]))
        C = corr_matrix.copy()

    C = np.abs(C)
    n = C.shape[0]

    # Fallback for very small matrices
    if n < 4:
        G = nx.Graph()
        G.add_nodes_from(labels)
        for u in range(n):
            for v in range(u + 1, n):
                G.add_edge(labels[u], labels[v], weight=C[u, v])
        return G

    # -----------------------------
    # Node strength
    # -----------------------------
    strength = C.sum(axis=1)

    # Initial 4-clique: top-4 strengths
    seed = np.argsort(strength)[-4:]

    G = nx.Graph()
    G.add_nodes_from(labels)

    # Add edges of the initial clique
    for i in range(4):
        for j in range(i + 1, 4):
            u, v = seed[i], seed[j]
            G.add_edge(labels[u], labels[v], weight=C[u, v])

    # -----------------------------
    # TMFG growth setup
    # -----------------------------
    # Pre-allocate gains matrix: maximum number of faces is 4 + 3*(n-4)
    max_faces = 4 + 3 * (n - 4)
    gains = np.full((n, max_faces), -np.inf)

    # Initial triangular faces
    faces = [
        (seed[0], seed[1], seed[2]),
        (seed[0], seed[1], seed[3]),
        (seed[0], seed[2], seed[3]),
        (seed[1], seed[2], seed[3])
    ]

    is_remaining = np.ones(n, dtype=bool)
    is_remaining[seed] = False

    # Compute initial gains
    for f_idx, f in enumerate(faces):
        gains[is_remaining, f_idx] = C[is_remaining, f[0]] + C[is_remaining, f[1]] + C[is_remaining, f[2]]

    next_face_idx = 4

    max_gain = np.full(n, -np.inf)
    best_face_idx_for_node = np.full(n, -1, dtype=int)

    rem_nodes = np.where(is_remaining)[0]
    if len(rem_nodes) > 0:
        best_f = np.argmax(gains[rem_nodes, :next_face_idx], axis=1)
        max_gain[rem_nodes] = gains[rem_nodes, best_f]
        best_face_idx_for_node[rem_nodes] = best_f

    # -----------------------------
    # TMFG growth loop
    # -----------------------------
    for _ in range(n - 4):
        # Find the global best remaining node and its best face
        best_node = np.argmax(max_gain)
        best_face_idx = best_face_idx_for_node[best_node]

        i, j, k = faces[best_face_idx]

        # Add edges
        G.add_edge(labels[best_node], labels[i], weight=C[best_node, i])
        G.add_edge(labels[best_node], labels[j], weight=C[best_node, j])
        G.add_edge(labels[best_node], labels[k], weight=C[best_node, k])

        # Update node state
        is_remaining[best_node] = False
        max_gain[best_node] = -np.inf
        gains[best_node, :] = -np.inf
        
        # Mark the face as removed
        gains[:, best_face_idx] = -np.inf

        # 3 new faces generated by the insertion
        new_faces = [
            (best_node, i, j),
            (best_node, i, k),
            (best_node, j, k)
        ]
        new_face_indices = [next_face_idx, next_face_idx + 1, next_face_idx + 2]

        rem_nodes = np.where(is_remaining)[0]
        if len(rem_nodes) == 0:
            break

        # Calculate gains for the new faces
        for f_idx, new_f in zip(new_face_indices, new_faces):
            faces.append(new_f)
            gains[rem_nodes, f_idx] = (
                C[rem_nodes, new_f[0]] + 
                C[rem_nodes, new_f[1]] + 
                C[rem_nodes, new_f[2]]
            )
        
        next_face_idx += 3

        # Update best faces for remaining nodes
        case1_mask = best_face_idx_for_node[rem_nodes] == best_face_idx
        case1_nodes = rem_nodes[case1_mask]
        case2_nodes = rem_nodes[~case1_mask]

        # Case 1: Nodes whose best face was just removed must recompute across ALL active faces
        if len(case1_nodes) > 0:
            best_f_case1 = np.argmax(gains[case1_nodes, :next_face_idx], axis=1)
            max_gain[case1_nodes] = gains[case1_nodes, best_f_case1]
            best_face_idx_for_node[case1_nodes] = best_f_case1

        # Case 2: Other nodes only need to check if any of the 3 new faces are better
        if len(case2_nodes) > 0:
            new_gains = gains[case2_nodes[:, None], new_face_indices]
            new_gains_max = np.max(new_gains, axis=1)
            new_gains_argmax = np.argmax(new_gains, axis=1)

            better_mask = new_gains_max > max_gain[case2_nodes]
            better_nodes = case2_nodes[better_mask]

            if len(better_nodes) > 0:
                max_gain[better_nodes] = new_gains_max[better_mask]
                best_face_idx_for_node[better_nodes] = np.array(new_face_indices)[new_gains_argmax[better_mask]]

    return G

def build_and_save_graph(year, speed, corr_dict):
    """
    Constroi grafo TMFG e salva em .pkl
    """
    corr_matrix = corr_dict[f"corr_{speed}_{year}"]
    G = get_network_TMFG(corr_matrix)  # não mostra barra aqui

    # Cria pasta se não existir
    base_path = f"../../data/04_graphs/{year}"
    os.makedirs(base_path, exist_ok=True)

    # Salva grafo
    file_path = os.path.join(base_path, f"{speed}_graph.pkl")
    nx.write_gpickle(G, file_path)

    return f"graph_{speed}_{year}", G