import json

notebook_path = "c:/Users/groque/Desktop/paper-financial-graph/code/trading/out_of_sample.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

new_cell_source = [
    "def out_of_sample_mcap_lead_lag(n_months: int):\n",
    "    years = range(2019, 2025)\n",
    "    \n",
    "    df_mcap_raw = pd.read_csv(\n",
    "        \"../../data/07_portfolios_metadata/all_tickers_complete_metadata.csv\"\n",
    "    )\n",
    "    \n",
    "    temp_list = []\n",
    "    \n",
    "    for year in years:\n",
    "        df_mcap = df_mcap_raw.copy()\n",
    "        \n",
    "        df_mcap[f\"mcap_{year}\"] = (\n",
    "            df_mcap[f\"mcap_{year}\"]\n",
    "            .replace(\"#ERROR!\", np.nan)\n",
    "            .astype(str)\n",
    "            .str.replace(\".\", \"\", regex=False)\n",
    "            .str.replace(\",\", \".\", regex=False)\n",
    "        )\n",
    "\n",
    "        df_mcap[f\"mcap_{year}\"] = pd.to_numeric(\n",
    "            df_mcap[f\"mcap_{year}\"],\n",
    "            errors=\"coerce\"\n",
    "        )\n",
    "\n",
    "        df_mcap[\"mcap_bin\"] = pd.qcut(\n",
    "            df_mcap[f\"mcap_{year}\"],\n",
    "            q=2,\n",
    "            labels=[\"Small\", \"Large\"],\n",
    "            duplicates=\"drop\"\n",
    "        )\n",
    "\n",
    "        returns_prev = pd.read_parquet(\n",
    "            f\"../../data/02_clean/returns_{year-9}_{year}.parquet\"\n",
    "        )\n",
    "\n",
    "        df_mcap = df_mcap[\n",
    "            df_mcap[\"Ticker\"].isin(returns_prev.columns)\n",
    "        ].copy()\n",
    "\n",
    "        small_tickers = df_mcap.loc[\n",
    "            df_mcap[\"mcap_bin\"] == \"Small\", \"Ticker\"\n",
    "        ].tolist()\n",
    "        large_tickers = df_mcap.loc[\n",
    "            df_mcap[\"mcap_bin\"] == \"Large\", \"Ticker\"\n",
    "        ].tolist()\n",
    "\n",
    "        end_date = (\n",
    "            pd.Timestamp(year=year + 1, month=n_months, day=1)\n",
    "            + pd.offsets.MonthEnd(0)\n",
    "        )\n",
    "        \n",
    "        path_ret = f\"../../data/02_clean/returns_{year + 1}.parquet\"\n",
    "        returns_oos = pd.read_parquet(path_ret).loc[:end_date]\n",
    "        \n",
    "        small_tickers_oos = [t for t in small_tickers if t in returns_oos.columns]\n",
    "        large_tickers_oos = [t for t in large_tickers if t in returns_oos.columns]\n",
    "        \n",
    "        log_ret_small = np.log1p(returns_oos[small_tickers_oos])\n",
    "        log_ret_large = np.log1p(returns_oos[large_tickers_oos])\n",
    "\n",
    "        # daily\n",
    "        R1 = log_ret_small.mean(axis=1)\n",
    "        R2 = log_ret_large.mean(axis=1)\n",
    "\n",
    "        # weekly\n",
    "        R3 = log_ret_small.resample(\"W-FRI\").sum().mean(axis=1)\n",
    "        R4 = log_ret_large.resample(\"W-FRI\").sum().mean(axis=1)\n",
    "\n",
    "        # 2-week\n",
    "        R5 = log_ret_small.resample(\"2W-FRI\").sum().mean(axis=1)\n",
    "        R6 = log_ret_large.resample(\"2W-FRI\").sum().mean(axis=1)\n",
    "\n",
    "        # monthly\n",
    "        R7 = log_ret_small.resample(\"ME\").sum().mean(axis=1)\n",
    "        R8 = log_ret_large.resample(\"ME\").sum().mean(axis=1)\n",
    "\n",
    "        pairs = [\n",
    "            (R1, R2),\n",
    "            (R3, R4),\n",
    "            (R5, R6),\n",
    "            (R7, R8)\n",
    "        ]\n",
    "\n",
    "        matrix = []\n",
    "        for R_small, R_large in pairs:\n",
    "            X = pd.concat([R_small, R_large], axis=1).dropna()\n",
    "            X.columns = [\"Small\", \"Large\"]\n",
    "            \n",
    "            acm = autocorrelation_matrix(X, lag=1)\n",
    "            lag_matrix = acm - acm.T\n",
    "            matrix.append(lag_matrix[1, 0])\n",
    "\n",
    "        df_year = pd.DataFrame(\n",
    "            [matrix], \n",
    "            index=[year + 1], \n",
    "            columns=[\"ls1d\", \"ls1w\", \"ls2w\", \"ls1m\"]\n",
    "        )\n",
    "        temp_list.append(df_year)\n",
    "\n",
    "    leadlag_df = pd.concat(temp_list)\n",
    "\n",
    "    # --- PLOTTING (Paper Style) ---\n",
    "    sns.set_theme(style=\"whitegrid\", context=\"paper\")\n",
    "    palette = sns.color_palette(\"colorblind\")\n",
    "\n",
    "    TITLE_SIZE, LABEL_SIZE = 25, 22\n",
    "    TICK_SIZE, LEGEND_SIZE = 18, 18\n",
    "    LINE_WIDTH, MARKER_SIZE = 2.5, 9\n",
    "\n",
    "    fig, axes = plt.subplots(2, 2, figsize=(18, 12), sharex=True, sharey=True)\n",
    "    axes_flat = axes.flatten()\n",
    "\n",
    "    panels = [\n",
    "        (\"ls1d\", f\"Next {n_months}-Months: 1-Day Lag\"),\n",
    "        (\"ls1w\", f\"Next {n_months}-Months: 1-Week Lag\"),\n",
    "        (\"ls2w\", f\"Next {n_months}-Months: 2-Weeks Lag\"),\n",
    "        (\"ls1m\", f\"Next {n_months}-Months: 1-Month Lag\"),\n",
    "    ]\n",
    "\n",
    "    for i, (ax, (col, title)) in enumerate(zip(axes_flat, panels)):\n",
    "        df = leadlag_df\n",
    "        ax.plot(\n",
    "            df.index, df[col],\n",
    "            lw=LINE_WIDTH, color=palette[2],\n",
    "            marker=\"^\", markersize=MARKER_SIZE,\n",
    "            label=\"Market Cap (Large vs Small)\", alpha=0.85\n",
    "        )\n",
    "\n",
    "        ax.set_title(title, fontsize=TITLE_SIZE, fontweight=\"bold\", pad=15)\n",
    "        ax.tick_params(axis=\"both\", labelsize=TICK_SIZE)\n",
    "        ax.axhline(0, color=\"black\", linewidth=2, linestyle=\"--\", alpha=0.6)\n",
    "        \n",
    "        if i >= 2: ax.set_xlabel(\"Year\", fontsize=LABEL_SIZE, fontweight=\"bold\")\n",
    "        if i % 2 == 0: ax.set_ylabel(\"Lead–Lag Measure\", fontsize=LABEL_SIZE, fontweight=\"bold\")\n",
    "        \n",
    "        ax.grid(alpha=0.3)\n",
    "\n",
    "    handles, labels = ax.get_legend_handles_labels()\n",
    "    fig.legend(\n",
    "        handles, labels,\n",
    "        loc=\"lower center\", ncol=1, frameon=False,\n",
    "        fontsize=LEGEND_SIZE, bbox_to_anchor=(0.5, -0.02)\n",
    "    )\n",
    "\n",
    "    sns.despine(fig=fig)\n",
    "    plt.tight_layout(rect=[0, 0.08, 1, 1])\n",
    "    plt.savefig(f\"../../figures/oos_mcap_leadlag_{n_months}.png\", dpi=300, bbox_inches=\"tight\")\n",
    "    plt.show()\n",
    "\n",
    "    return leadlag_df\n"
]

new_cell = {
    "cell_type": "code",
    "execution_count": None,
    "id": "a1b2c3d4",
    "metadata": {},
    "outputs": [],
    "source": new_cell_source
}

nb["cells"].append(new_cell)

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)
